name: coremvp
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.7.0
  firebase_auth:
  google_sign_in:
  sqflite: ^0.7.1
  path_provider: ^0.4.0
  http:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  web_socket_channel:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
     - family: osSys
       fonts:
         - asset: fonts/KhmerOSsys.ttf
#   - family: Trajan Pro
#      fonts:
#       - asset: fonts/TrajanPro.ttf
#      - asset: fonts/TrajanPro_Bold.ttf
#       weight: 700
  
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
